name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ] # Dispara o deploy sempre que houver um push na branch principal (main)

  jobs: 
    deploy:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v1
            with:
              node-version: 24
          - run npm ci
          - run npm run test